"""stage7_workflow_orchestration

Revision ID: ac4ab5a2363a
Revises: 3da48f665662
Create Date: 2026-04-01 09:43:06.429722
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac4ab5a2363a'
down_revision: Union[str, None] = '3da48f665662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('workflow_type', sa.String(length=128), nullable=False),
    sa.Column('cron_expression', sa.String(length=128), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_id', sa.Integer(), nullable=True),
    sa.Column('last_status', sa.String(length=32), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_sched_job_active', 'scheduled_jobs', ['is_active'], unique=False)
    op.create_index('ix_sched_job_next', 'scheduled_jobs', ['next_run_at'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('workflow_type', sa.String(length=128), nullable=False),
    sa.Column('idempotency_key', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('current_step', sa.String(length=128), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('completed_steps', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.Column('triggered_by', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_wf_run_status', 'workflow_runs', ['status'], unique=False)
    op.create_index('ix_wf_run_tenant', 'workflow_runs', ['tenant_id'], unique=False)
    op.create_index('ix_wf_run_type', 'workflow_runs', ['workflow_type'], unique=False)
    op.create_table('workflow_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_run_id', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=128), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_retryable', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wf_step_run', 'workflow_steps', ['workflow_run_id'], unique=False)
    op.create_index('ix_wf_step_status', 'workflow_steps', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wf_step_status', table_name='workflow_steps')
    op.drop_index('ix_wf_step_run', table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_index('ix_wf_run_type', table_name='workflow_runs')
    op.drop_index('ix_wf_run_tenant', table_name='workflow_runs')
    op.drop_index('ix_wf_run_status', table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index('ix_sched_job_next', table_name='scheduled_jobs')
    op.drop_index('ix_sched_job_active', table_name='scheduled_jobs')
    op.drop_table('scheduled_jobs')
    # ### end Alembic commands ###
