"""stage5_adaptation_self_improving

Revision ID: bb614cd4019d
Revises: 0005_outbox_dedup
Create Date: 2026-04-01 07:26:46.233384
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb614cd4019d'
down_revision: Union[str, None] = '0005_outbox_dedup'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adaptation_experiments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('experiment_type', sa.String(length=64), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('baseline_profile_json', sa.JSON(), nullable=False),
    sa.Column('candidate_profile_json', sa.JSON(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('baseline_metrics_json', sa.JSON(), nullable=False),
    sa.Column('candidate_metrics_json', sa.JSON(), nullable=False),
    sa.Column('comparison_json', sa.JSON(), nullable=True),
    sa.Column('verdict', sa.String(length=32), nullable=True),
    sa.Column('verdict_reason', sa.Text(), nullable=True),
    sa.Column('items_evaluated', sa.Integer(), nullable=False),
    sa.Column('degradation_threshold', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_experiment_status', 'adaptation_experiments', ['status'], unique=False)
    op.create_table('adaptation_proposals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('proposal_type', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=False),
    sa.Column('current_value_json', sa.JSON(), nullable=False),
    sa.Column('proposed_value_json', sa.JSON(), nullable=False),
    sa.Column('delta_json', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('evaluation_run_id', sa.Integer(), nullable=True),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('simulation_result_json', sa.JSON(), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rolled_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proposal_status', 'adaptation_proposals', ['status'], unique=False)
    op.create_index('ix_proposal_tenant', 'adaptation_proposals', ['tenant_id'], unique=False)
    op.create_table('adaptation_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_adapt_ver_profile', 'adaptation_versions', ['profile_id'], unique=False)
    op.create_table('adaptive_scoring_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('base_score', sa.Float(), nullable=False),
    sa.Column('adjusted_score', sa.Float(), nullable=False),
    sa.Column('adjustments_json', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_asl_entity', 'adaptive_scoring_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('adaptive_scoring_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('weights_json', sa.JSON(), nullable=False),
    sa.Column('source_trust_json', sa.JSON(), nullable=False),
    sa.Column('category_trust_json', sa.JSON(), nullable=False),
    sa.Column('thresholds_json', sa.JSON(), nullable=False),
    sa.Column('calibration_json', sa.JSON(), nullable=False),
    sa.Column('safe_bounds_json', sa.JSON(), nullable=False),
    sa.Column('parent_profile_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_asp_tenant_name')
    )
    op.create_index('ix_asp_tenant', 'adaptive_scoring_profiles', ['tenant_id'], unique=False)
    op.create_table('evaluation_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_label', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=False),
    sa.Column('comparison_json', sa.JSON(), nullable=True),
    sa.Column('degradation_flags', sa.JSON(), nullable=False),
    sa.Column('improvement_flags', sa.JSON(), nullable=False),
    sa.Column('sample_counts', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_eval_run_status', 'evaluation_runs', ['status'], unique=False)
    op.create_index('ix_eval_run_tenant', 'evaluation_runs', ['tenant_id'], unique=False)
    op.create_table('feedback_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('feedback_type', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('usefulness_rating', sa.Integer(), nullable=True),
    sa.Column('confidence_rating', sa.Float(), nullable=True),
    sa.Column('reviewer', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('evidence_snapshot', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_created', 'feedback_events', ['created_at'], unique=False)
    op.create_index('ix_feedback_target', 'feedback_events', ['target_type', 'target_id'], unique=False)
    op.create_index('ix_feedback_tenant', 'feedback_events', ['tenant_id'], unique=False)
    op.create_table('goal_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_metric', sa.String(length=128), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('guardrails_json', sa.JSON(), nullable=False),
    sa.Column('segment_type', sa.String(length=64), nullable=True),
    sa.Column('segment_value', sa.String(length=255), nullable=True),
    sa.Column('evaluation_window', sa.String(length=32), nullable=False),
    sa.Column('adaptation_strategy', sa.String(length=64), nullable=False),
    sa.Column('approval_mode', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_goal_tenant', 'goal_definitions', ['tenant_id'], unique=False)
    op.create_table('metric_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evaluation_run_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=128), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('segment_type', sa.String(length=64), nullable=True),
    sa.Column('segment_value', sa.String(length=255), nullable=True),
    sa.Column('previous_value', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('is_degraded', sa.Boolean(), nullable=False),
    sa.Column('is_improved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_metric_snap_eval', 'metric_snapshots', ['evaluation_run_id'], unique=False)
    op.create_index('ix_metric_snap_name', 'metric_snapshots', ['metric_name'], unique=False)
    op.create_table('optimization_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('progress_pct', sa.Float(), nullable=True),
    sa.Column('candidate_proposals', sa.JSON(), nullable=False),
    sa.Column('trade_offs_json', sa.JSON(), nullable=False),
    sa.Column('guardrail_violations', sa.JSON(), nullable=False),
    sa.Column('recommendations_json', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outcome_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('outcome_type', sa.String(length=64), nullable=False),
    sa.Column('outcome_value', sa.String(length=255), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('measurement_window_hours', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outcome_created', 'outcome_records', ['created_at'], unique=False)
    op.create_index('ix_outcome_entity', 'outcome_records', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_outcome_tenant', 'outcome_records', ['tenant_id'], unique=False)
    op.create_table('rollback_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('from_version', sa.Integer(), nullable=False),
    sa.Column('to_version', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('rolled_back_by', sa.String(length=255), nullable=False),
    sa.Column('metrics_before_json', sa.JSON(), nullable=False),
    sa.Column('metrics_after_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('self_evaluation_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('report_type', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=False),
    sa.Column('metrics_before_json', sa.JSON(), nullable=False),
    sa.Column('metrics_after_json', sa.JSON(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_trust_current',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('topic_key', sa.String(length=255), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('noise_score', sa.Float(), nullable=False),
    sa.Column('timeliness_score', sa.Float(), nullable=False),
    sa.Column('confirmation_rate', sa.Float(), nullable=False),
    sa.Column('volatility_score', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_name', 'topic_key', name='uq_source_trust')
    )
    op.create_index('ix_stc_tenant_source', 'source_trust_current', ['tenant_id', 'source_name'], unique=False)
    op.create_table('source_trust_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('noise_score', sa.Float(), nullable=False),
    sa.Column('timeliness_score', sa.Float(), nullable=False),
    sa.Column('confirmation_rate', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sth_source', 'source_trust_history', ['source_name'], unique=False)
    op.create_index('ix_sth_tenant', 'source_trust_history', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('fk_score_records_tenant'), 'score_records', type_='foreignkey')
    op.drop_constraint(op.f('fk_score_records_workspace'), 'score_records', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_score_records_workspace'), 'score_records', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_score_records_tenant'), 'score_records', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_sth_tenant', table_name='source_trust_history')
    op.drop_index('ix_sth_source', table_name='source_trust_history')
    op.drop_table('source_trust_history')
    op.drop_index('ix_stc_tenant_source', table_name='source_trust_current')
    op.drop_table('source_trust_current')
    op.drop_table('self_evaluation_reports')
    op.drop_table('rollback_records')
    op.drop_index('ix_outcome_tenant', table_name='outcome_records')
    op.drop_index('ix_outcome_entity', table_name='outcome_records')
    op.drop_index('ix_outcome_created', table_name='outcome_records')
    op.drop_table('outcome_records')
    op.drop_table('optimization_runs')
    op.drop_index('ix_metric_snap_name', table_name='metric_snapshots')
    op.drop_index('ix_metric_snap_eval', table_name='metric_snapshots')
    op.drop_table('metric_snapshots')
    op.drop_index('ix_goal_tenant', table_name='goal_definitions')
    op.drop_table('goal_definitions')
    op.drop_index('ix_feedback_tenant', table_name='feedback_events')
    op.drop_index('ix_feedback_target', table_name='feedback_events')
    op.drop_index('ix_feedback_created', table_name='feedback_events')
    op.drop_table('feedback_events')
    op.drop_index('ix_eval_run_tenant', table_name='evaluation_runs')
    op.drop_index('ix_eval_run_status', table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_index('ix_asp_tenant', table_name='adaptive_scoring_profiles')
    op.drop_table('adaptive_scoring_profiles')
    op.drop_index('ix_asl_entity', table_name='adaptive_scoring_logs')
    op.drop_table('adaptive_scoring_logs')
    op.drop_index('ix_adapt_ver_profile', table_name='adaptation_versions')
    op.drop_table('adaptation_versions')
    op.drop_index('ix_proposal_tenant', table_name='adaptation_proposals')
    op.drop_index('ix_proposal_status', table_name='adaptation_proposals')
    op.drop_table('adaptation_proposals')
    op.drop_index('ix_experiment_status', table_name='adaptation_experiments')
    op.drop_table('adaptation_experiments')
    # ### end Alembic commands ###
